import { MRT_Localization } from "material-react-table";

export const MRT_Localization_FI: MRT_Localization = {
  actions: 'Toiminnot',
  and: 'ja',
  cancel: 'Peruuta',
  changeFilterMode: 'Vaihda suodatusta',
  changeSearchMode: 'Vaihda hakua',
  clearFilter: 'Nollaa suodatus',
  clearSearch: 'Nollaa haku',
  clearSort: 'Nollaa järjestys',
  clickToCopy: 'Paina kopioidaksesi',
  collapse: 'Sulje',
  collapseAll: 'Sulje kaikki',
  columnActions: 'Saraketoiminnot',
  copiedToClipboard: 'Kopioitu leikepöydälle',
  dropToGroupBy: 'Pudota ryhmittääksesi sarake {column}',
  edit: 'Muokkaa',
  expand: 'Avaa',
  expandAll: 'Avaa kaikki',
  filterArrIncludes: 'Sisältää',
  filterArrIncludesAll: 'Sisältää kaikki',
  filterArrIncludesSome: 'Sisältää',
  filterBetween: 'Välillä',
  filterBetweenInclusive: 'Välillä (inklusiivinen)',
  filterByColumn: '',
  filterContains: 'Sisältää',
  filterEmpty: 'Tyhjä',
  filterEndsWith: 'Loppuu',
  filterEquals: 'Yhtäsuuri',
  filterEqualsString: 'Yhtäsuuri',
  filterFuzzy: 'Epätarkka',
  filterGreaterThan: 'Suurempi kuin',
  filterGreaterThanOrEqualTo: 'Suurempi tai yhtäsuuri',
  filterInNumberRange: 'Välillä',
  filterIncludesString: 'Sisältää',
  filterIncludesStringSensitive: 'Sisältää',
  filterLessThan: 'Vähemmän kuin',
  filterLessThanOrEqualTo: 'Vähemmän tai yhtäsuuri',
  filterMode: 'Suodatus: {filterType}',
  filterNotEmpty: 'Ei tyhjä',
  filterNotEquals: 'Ei yhtäsuuri',
  filterStartsWith: 'Alkaa',
  filterWeakEquals: 'Yhtäsuuri',
  filteringByColumn: 'Suodatetaan sarakkeella {column} - {filterType} {filterValue}',
  goToFirstPage: 'Go to first page',
  goToLastPage: 'Go to last page',
  goToNextPage: 'Go to next page',
  goToPreviousPage: 'Go to previous page',
  grab: 'Tartu',
  groupByColumn: 'Ryhmitä sarakkeella {column}',
  groupedBy: 'Järjestetty ',
  hideAll: 'Piilota kaikki',
  hideColumn: 'Piilota sarake {column}',
  max: 'Max',
  min: 'Min',
  move: 'Liikuta',
  noRecordsToDisplay: 'Ei näytettävää',
  noResultsFound: 'Ei hakutuloksia',
  of: '/',
  or: 'tai',
  pinToLeft: 'Kiinnitä vasemmalle',
  pinToRight: 'Kiinnitä oikealle',
  resetColumnSize: 'Nollaa sarakkeen koko',
  resetOrder: 'Nollaa järjestys',
  rowActions: 'Rivitoiminnot',
  rowNumber: '#',
  rowNumbers: 'Rivinumerot',
  rowsPerPage: 'Riviä sivulla',
  save: 'Tallenna',
  search: 'Haku',
  selectedCountOfRowCountRowsSelected: '{selectedCount}/{rowCount} rivi(ä) valittuna',
  select: 'Valitse',
  showAll: 'Näytä kaikki',
  showAllColumns: 'Näytä kaikki sarakkeet',
  showHideColumns: 'Näytä/Piilota sarakkeet',
  showHideFilters: 'Näytä/Piilota suodattimet',
  showHideSearch: 'Näytä/Piilota haku',
  sortByColumnAsc: 'Järjestä sarakkeella {column} nousevasti',
  sortByColumnDesc: 'Järjestä sarakkeella {column} laskevasti',
  sortedByColumnAsc: 'Järjestetty sarakkeella {column} nousevasti',
  sortedByColumnDesc: 'Järjestetty sarakkeella {column} laskevasti',
  thenBy: ', ja sitten ',
  toggleDensity: 'Vaihda tiiviyttä',
  toggleFullScreen: 'Vaihda kokonäyttötilaa',
  toggleSelectAll: 'Vaihda kaikkien valintaa',
  toggleSelectRow: 'Vaihda rivivalintaa',
  toggleVisibility: 'Vaihda näkyvyyttä',
  ungroupByColumn: 'Poista sarakkeen {column} ryhmitys',
  unpin: 'Irrota',
  unpinAll: 'Irrota kaikki',
  pin: "Kiinnitä"
};